/**
 * PDF Export utilities for HisabBazaar.
 *
 * Generates a real, downloadable PDF from the currently displayed data using
 * jsPDF + jspdf-autotable. All currency values are formatted in the
 * Indian numbering system (e.g. INR 12,34,567.89) which renders correctly in
 * the default PDF fonts.
 */
import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import type { ProfitCalculationResult, BusinessSettings, ProductItem } from '../types';
import { formatNumberIndian } from './formatters';

const PAGE_W = 210; // A4 width in mm
const PAGE_H = 297; // A4 height in mm
const MARGIN = 14;
const CONTENT_W = PAGE_W - MARGIN * 2; // 182mm

const INDIGO: [number, number, number] = [79, 70, 229];
const SLATE_600: [number, number, number] = [71, 85, 105];
const SLATE_400: [number, number, number] = [148, 163, 184];
const DARK_TEXT: [number, number, number] = [30, 41, 59];
const EMERALD: [number, number, number] = [16, 185, 129];
const ROSE: [number, number, number] = [244, 63, 94];

/**
 * Format a number as an INR amount in the Indian numbering system.
 * Returns a string like "INR 1,29,999.00" (or "INR 0" when decimals disabled).
 */
function formatINRPdf(val: number | undefined | null, showDecimals = true): string {
  if (val === undefined || val === null || isNaN(val)) {
    return showDecimals ? 'INR 0.00' : 'INR 0';
  }
  const abs = Math.abs(val);
  const fixed = abs.toFixed(showDecimals ? 2 : 0);
  const parts = fixed.split('.');
  const integerPart = parts[0];
  const decimalPart = parts[1];

  let grouped: string;
  if (integerPart.length <= 3) {
    grouped = integerPart;
  } else {
    const last3 = integerPart.slice(-3);
    const rest = integerPart.slice(0, -3);
    grouped = rest.replace(/\B(?=(\d{2})+(?!\d))/g, ',') + ',' + last3;
  }

  const sign = val < 0 ? '-' : '';
  const amount = showDecimals && decimalPart !== undefined
    ? `${grouped}.${decimalPart}`
    : grouped;
  return `${sign}INR ${amount}`;
}

/**
 * Format a number as a plain Indian-grouped amount, e.g. "1,29,999".
 */
function formatIndianNumberPdf(val: number | undefined | null): string {
  if (val === undefined || val === null || isNaN(val)) return '0';
  return formatNumberIndian(val);
}

/**
 * Strip characters that the PDF's built-in WinAnsi font cannot render
 * (emojis, CJK, exotic unicode) and replace them with a safe fallback.
 */
function sanitizePdfText(text: string | null | undefined, fallback = ''): string {
  if (text === null || text === undefined) return fallback;
  return text
    .replace(/\s+/g, ' ')
    .split('')
    .map((ch) => {
      const code = ch.codePointAt(0) || 0;
      // Keep printable ASCII + common latin-1 letters/punctuation.
      if (
        (code >= 0x20 && code <= 0x7e) || // ASCII printable
        (code >= 0xa0 && code <= 0xff) || // Latin-1 supplement
        code === 0x2013 || // en dash
        code === 0x2014 || // em dash
        code === 0x2018 || code === 0x2019 || // curly quotes
        code === 0x201c || code === 0x201d ||
        code === 0x2022 || // bullet
        code === 0x2026 || // ellipsis
        code === 0x20b9 // rupee sign
      ) {
        return ch;
      }
      return '';
    })
    .join('')
    .replace(/₹/g, 'Rs.')
    .trim();
}

/**
 * Draw the branded header band used on every generated page (first page gets
 * a full header, later pages a slim one).
 */
function drawPageHeader(
  doc: jsPDF,
  title: string,
  subtitle: string,
  pageNumber: number,
  totalPages: number,
) {
  // Header band
  doc.setFillColor(INDIGO[0], INDIGO[1], INDIGO[2]);
  doc.rect(0, 0, PAGE_W, 22, 'F');

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(14, 5, 9, 9, 1.5, 1.5, 'F');
  doc.setTextColor(INDIGO[0], INDIGO[1], INDIGO[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('₹', 18.5, 11.2);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.text('HisabBazaar', 27, 10.2);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(196, 181, 253);
  doc.text('Profit • Fee • GST Calculator for Indian Sellers', 27, 15.5);

  // Title on the right side of the header band
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  const rightTitle = sanitizePdfText(title, 'Report');
  doc.text(rightTitle, PAGE_W - MARGIN, 10.5, { align: 'right', maxWidth: 100 });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(221, 214, 254);
  doc.text(
    sanitizePdfText(subtitle, 'Generated by HisabBazaar'),
    PAGE_W - MARGIN,
    15.5,
    { align: 'right', maxWidth: 110 },
  );
}

function drawPageFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, PAGE_H - 12, PAGE_W - MARGIN, PAGE_H - 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...SLATE_400);
  doc.text('HisabBazaar — Confidential financial estimate. Verify against official statements.', MARGIN, PAGE_H - 7);

  doc.setTextColor(...SLATE_600);
  doc.text(`Page ${pageNumber} of ${totalPages}`, PAGE_W - MARGIN, PAGE_H - 7, { align: 'right' });
}

/**
 * Convert a ProfitCalculationResult (the data shown on the "Profit & Loss"
 * results screen) into a branded multi-page PDF and trigger a download.
 */
export function generateCalculationPdf(
  result: ProfitCalculationResult,
  settings: BusinessSettings,
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const input = result.input;
  const dateLabel = new Date(result.timestamp || Date.now()).toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const productTitle = sanitizePdfText(input.productName, 'Custom Product');

  // ---------- Header band ----------
  drawPageHeader(
    doc,
    'Profit & Loss Analysis',
    `${sanitizePdfText(settings.businessName || 'Seller Hub', 'Seller Hub')} • ${dateLabel}`,
    1,
    0,
  );

  // ---------- Document meta block ----------
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...DARK_TEXT);
  doc.text(productTitle, MARGIN, 32);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...SLATE_600);
  doc.text(`Marketplace: ${input.marketplace.toUpperCase()}${input.sku ? `   •   SKU: ${sanitizePdfText(input.sku)}` : ''}`, MARGIN, 38);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 42, PAGE_W - MARGIN, 42);

  // ---------- Big result highlight ----------
  const isProfitable = result.isProfitable;
  const highlightColor: [number, number, number] = isProfitable ? [5, 150, 105] : [190, 18, 60];
  doc.setFillColor(highlightColor[0], highlightColor[1], highlightColor[2]);
  doc.roundedRect(MARGIN, 46, CONTENT_W, 26, 4, 4, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('NET IN-POCKET PROFIT (PER UNIT)', MARGIN + 4, 53);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  const profitStr = formatINRPdf(result.netProfit);
  doc.text(isProfitable ? `+${profitStr}` : profitStr, MARGIN + 4, 64);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(
    `${isProfitable ? 'Profitable Unit' : 'Loss Making'}   •   ${result.profitMarginPercent.toFixed(1)}% margin   •   ROI ${result.roiPercent.toFixed(1)}%`,
    MARGIN + 4,
    69,
  );

  // ---------- Key metrics ----------
  autoTable(doc, {
    startY: 78,
    margin: { left: MARGIN, right: MARGIN },
    theme: 'grid',
    head: [['Metric', 'Value', 'Metric', 'Value']],
    body: [
      [
        'Selling Price (Gross Revenue)',
        formatINRPdf(result.grossRevenue),
        'Break-Even Price',
        formatINRPdf(result.breakEvenSellingPrice, false),
      ],
      [
        'Net Selling Price (after discount)',
        formatINRPdf(result.netSellingPrice),
        'Bank Settlement (Payout)',
        formatINRPdf(result.moneyReceivedFromMarketplace),
      ],
      [
        'GST on Product',
        formatINRPdf(result.gstAmount),
        'Recommended Sell Price (target)',
        formatINRPdf(result.recommendedSellingPriceForTarget, false),
      ],
      [
        'Profit Margin',
        `${result.profitMarginPercent.toFixed(1)}%`,
        'Return on Investment (ROI)',
        `${result.roiPercent.toFixed(1)}%`,
      ],
    ],
    styles: { fontSize: 8.5, cellPadding: 2.5, textColor: DARK_TEXT },
    headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 8.5, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 41 },
      2: { fontStyle: 'bold', cellWidth: 50 },
      3: { cellWidth: 41 },
    },
  });

  // ---------- Cost breakdown table ----------
  const feesBreakdown: [string, number][] = [
    ['Marketplace Commission', result.input.commissionRate * result.netSellingPrice / 100],
    [`GST on Marketplace Fees (18%)`, result.marketplaceGst],
    ['Fixed / Closing Fee', result.fixedFee],
    ['Shipping Fee', result.shippingFee],
    ['Payment Gateway Fee', result.paymentGatewayFee],
  ];
  const filledFees = feesBreakdown.filter(([, v]) => v > 0);
  const tableBody: (string | number)[][] = [
    ['Product Sourcing Cost (Base)', result.productCostTotal],
    ['GST Amount ({rate}%)'.replace('{rate}', String(input.gstRate)), result.gstAmount],
    ...filledFees.map(([label, v]) => [label, v] as (string | number)[]),
    ['Packaging Cost', result.packagingCostTotal],
    ['Advertising & Marketing', result.advertisingCostTotal],
    ['Other Operating Expenses', result.otherExpensesTotal],
    ['Return / RTO Risk Allowance', result.returnRiskCost],
  ].filter((row) => (typeof row[1] === 'number' ? row[1] > 0 : true));

  const tableStartY = (doc as any).lastAutoTable?.finalY ?? 78;
  autoTable(doc, {
    startY: tableStartY + 8,
    margin: { left: MARGIN, right: MARGIN },
    theme: 'grid',
    head: [['Cost Component', 'Amount (INR)']],
    body: [
      ...tableBody,
      ['Total Cost', result.totalCosts],
    ],
    styles: { fontSize: 8.5, cellPadding: 2.5, textColor: DARK_TEXT },
    headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 8.5, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === tableBody.length) {
        // Total row emphasized
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [238, 242, 255];
      }
    },
  });

  // ---------- Summary statement ----------
  const finalY = (doc as any).lastAutoTable?.finalY ?? 100;
  if (finalY > PAGE_H - 45) {
    doc.addPage();
  }

  const summaryStart = (doc as any).lastAutoTable?.finalY ?? finalY;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...DARK_TEXT);
  doc.text('Executive Summary', MARGIN, summaryStart + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...SLATE_600);
  const summaryLines = [
    `• Gross Revenue: ${formatINRPdf(result.grossRevenue)} with ${formatIndianNumberPdf(result.netSellingPrice)} net after discount.`,
    `• Total Deductions: ${formatINRPdf(result.totalCosts)} (sourcing, GST, marketplace fees, operating & risk costs).`,
    `• Net Profit: ${isProfitable ? '+' : ''}${formatINRPdf(result.netProfit)} → ${result.profitMarginPercent.toFixed(1)}% margin on revenue.`,
    `• Bank Settlement: ${formatINRPdf(result.moneyReceivedFromMarketplace)} is what you receive from the marketplace.`,
    `• Safety Price: never sell below ${formatINRPdf(result.breakEvenSellingPrice, false)} to avoid a loss.`,
  ];
  doc.text(summaryLines, MARGIN, summaryStart + 16);

  // ---------- Footer (all pages) ----------
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i > 1) {
      drawPageHeader(doc, 'Profit & Loss Analysis', productTitle, i, totalPages);
    }
    drawPageFooter(doc, i, totalPages);
  }

  const safeName = productTitle.replace(/[^\w-]+/g, '_').slice(0, 50) || 'calculation';
  doc.save(`HisabBazaar_ProfitLoss_${safeName}.pdf`);
}

/**
 * Build the itemized row list (shared between CSV and PDF report exports).
 * Prioritizes calculation history; falls back to catalog products.
 */
export function buildReportRows(
  history: ProfitCalculationResult[],
  products: ProductItem[],
): {
  rows: (string | number)[][];
  hasData: boolean;
} {
  if (history.length > 0) {
    return {
      hasData: true,
      rows: history.map((item) => [
        new Date(item.timestamp).toISOString().split('T')[0],
        item.input.marketplace.toUpperCase(),
        sanitizePdfText(item.input.productName) || 'Product',
        item.input.sku ? sanitizePdfText(item.input.sku) : '—',
        formatINRPdf(item.input.sellingPrice, false),
        formatINRPdf(item.input.productCost),
        formatINRPdf(item.gstAmount),
        formatINRPdf(item.totalMarketplaceFees),
        formatINRPdf(item.netProfit),
        `${item.profitMarginPercent.toFixed(1)}%`,
      ]),
    };
  }
  if (products.length > 0) {
    return {
      hasData: true,
      rows: products.map((p) => [
        new Date(p.createdAt).toISOString().split('T')[0],
        p.marketplace.toUpperCase(),
        sanitizePdfText(p.name),
        sanitizePdfText(p.sku) || '—',
        formatINRPdf(p.sellingPrice, false),
        formatINRPdf(p.productCost),
        formatINRPdf(p.sellingPrice * (p.gstRate / (100 + p.gstRate))),
        formatINRPdf((p.commissionRate / 100) * p.sellingPrice + p.fixedFee + p.shippingFee),
        formatINRPdf(p.netProfit),
        `${p.profitMargin.toFixed(1)}%`,
      ]),
    };
  }
  return { rows: [], hasData: false };
}

/**
 * Generate a comprehensive report PDF from the on-screen report aggregates.
 * Handles multi-page (auto page breaks), empty data gracefully, and includes
 * a branded layout with accurate figures taken directly from the UI state.
 */
export function generateReportPdf(
  report: {
    totalSales: number;
    totalProfit: number;
    totalExpenses: number;
    totalFees: number;
    totalGst: number;
    totalProductCost: number;
    totalShipping: number;
    totalAds: number;
    orders: number;
    aov: number;
    margin: number;
  },
  history: ProfitCalculationResult[],
  products: ProductItem[],
  settings: BusinessSettings,
  dateFilterLabel: string,
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const generatedAt = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // ---------- Header ----------
  drawPageHeader(
    doc,
    'Business Financial Report',
    `${sanitizePdfText(settings.businessName || 'Business Reports', 'Business Reports')} • ${generatedAt}`,
    1,
    0,
  );

  // ---------- Zero / empty state ----------
  if (!report || report.totalSales <= 0) {
    const { hasData } = buildReportRows(history, products);
    if (!hasData) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(...DARK_TEXT);
      doc.text('No Data Available', MARGIN, 42);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...SLATE_600);
      doc.text(
        'There is no financial data to export yet. Calculate a product or add items to your catalog, then export again.',
        MARGIN,
        48,
        { maxWidth: CONTENT_W },
      );

      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        drawPageFooter(doc, i, totalPages);
      }
      doc.save('HisabBazaar_EmptyReport.pdf');
      return;
    }
  }

  // ---------- Business / summary block ----------
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...DARK_TEXT);
  doc.text(`Financial Summary${dateFilterLabel ? ` — ${dateFilterLabel}` : ''}`, MARGIN, 30);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 33.5, PAGE_W - MARGIN, 33.5);

  autoTable(doc, {
    startY: 37,
    margin: { left: MARGIN, right: MARGIN },
    theme: 'grid',
    head: [['Summary Metric', 'Value', 'Summary Metric', 'Value']],
    body: [
      ['Gross Revenue', formatINRPdf(report.totalSales), 'Total Expenses', formatINRPdf(report.totalExpenses)],
      ['Net Profit', formatINRPdf(report.totalProfit), 'Profit Margin', `${report.margin.toFixed(1)}%`],
      ['Marketplace Fees', formatINRPdf(report.totalFees), 'GST Liability', formatINRPdf(report.totalGst)],
      ['Product / Inventory Cost', formatINRPdf(report.totalProductCost), 'Shipping & Ads', formatINRPdf(report.totalShipping + report.totalAds)],
      ['Tracked Orders', String(report.orders), 'Average Order Value', formatINRPdf(report.aov)],
    ],
    styles: { fontSize: 8.5, cellPadding: 2.5, textColor: DARK_TEXT },
    headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 8.5, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 41 },
      2: { fontStyle: 'bold', cellWidth: 50 },
      3: { cellWidth: 41 },
    },
  });

  // ---------- Itemized records ----------
  const { rows, hasData } = buildReportRows(history, products);
  const tableStart = (doc as any).lastAutoTable?.finalY ?? 37;

  autoTable(doc, {
    startY: tableStart + 8,
    margin: { left: MARGIN, right: MARGIN },
    theme: 'striped',
    head: [['Date', 'Channel', 'Product', 'SKU', 'Selling', 'Cost', 'GST', 'Fees', 'Profit', 'Margin']],
    body: rows,
    styles: { fontSize: 7.5, cellPadding: 2, textColor: DARK_TEXT },
    headStyles: { fillColor: INDIGO, textColor: 255, fontSize: 7.5, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  if (!hasData) {
    const noteStart = (doc as any).lastAutoTable?.finalY ?? tableStart + 8;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(...SLATE_400);
    doc.text('No itemized records available — summary values above are based on your current view.', MARGIN, noteStart + 6);
  }

  // ---------- Footers ----------
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i > 1) {
      drawPageHeader(doc, 'Business Financial Report', sanitizePdfText(settings.businessName || 'Business Reports'), i, totalPages);
    }
    drawPageFooter(doc, i, totalPages);
  }

  doc.save(`HisabBazaar_Report_${dateFilterLabel ? dateFilterLabel.replace(/\s+/g, '_') : 'all'}.pdf`);
}